
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: tomm_development
  pool: 5
  timeout: 5000
  template: template0

test:
  adapter: postgresql
  database: tomm_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tomm_production
  pool: 5
  timeout: 5000
